#- name: Baseline
#  hosts: all
#  tasks:
#  - 
- name: Install Wordpress
  hosts: wordpress_hosts
  tasks:
  - command: "echo $(hostname) is running wordpress!"

- name: Install SQL
  hosts: sql_hosts
  become: yes
  ignore_errors: yes
  tasks:
  - command: "echo $(hostname) is running sql!"
  - script: "scripts/mysql.sh"

- name: Install vsftpd
  hosts: vsftpd_hosts
  tasks:
  - command: "echo $(hostname) is running vsftpd!"
